apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paxos
  template:
    metadata:
      labels:
        app: paxos
    spec:
      containers:
        - name: paxos
          image: web-service/paxos:latest
          ports:
            - containerPort: 8080
